import Head from 'next/head'
import Image from 'next/image'
import React, { useRef, useEffect } from 'react';
import lottie from 'lottie-web';
import PC from '../../public/1.json'
import digikala from '../../public/Digikala.svg.png'
import snapp from '../../public/snapp.png'
import stjoes from '../../public/stjoes.png'
import shorty from '../../public/shorty.png'
import Aryan from '../../public/Aryan.png'
import Dentist from '../../public/Dentist.png'
import flexday from '../../public/flexday.png'
import styles from '@/styles/Home.module.css'
import LinkedInIcon from '@mui/icons-material/LinkedIn';
import GitHubIcon from '@mui/icons-material/GitHub';
import ArrowDropDownCircleIcon from '@mui/icons-material/ArrowDropDownCircle';
import { height } from '@mui/system'


export default function Home() {

  const lottieRef = useRef(null);

useEffect(() => {
  const instance = lottie.loadAnimation({
    container: lottieRef.current ?? undefined, // add a null-check here
    renderer: 'svg',
    loop: true,
    autoplay: true,
    animationData: PC
  });
  return () => instance.destroy();
}, []);
  

  return (
    <>
      <Head>
        <title>Ali Tehrani</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <main>
      
        <section className='p-6 bg-[conic-gradient(at_bottom,_var(--tw-gradient-stops))] from-gray-900 via-blue-900 to-gray-900'>
          
          <div className='flex justify-between items-center mb-14 md:-mb-10'>
        <div className=''>
          <h1 className='text-indigo-700 text-3xl font-extrabold 2xl:text-6xl md:text-6xl'>Ali</h1>
          <h1 className='text-sky-500 text-3xl font-extrabold 2xl:text-6xl md:text-6xl'>Tehrani</h1>
        </div>
        <div className='flex gap-3'>
          <a href='https://github.com/alittehrani'><GitHubIcon className='text-white text-4xl 2xl:text-7xl md:text-5xl'/></a>
          <LinkedInIcon className='text-blue-600 text-4xl 2xl:text-7xl md:text-5xl'/>
        </div>
        </div>

        <div className='flex justify-center items-center flex-col'>
          <h1 className='text-white text-center text-4xl font-extrabold md:text-7xl md:mt-10 2xl:text-9xl 2xl:-mt-10 md:mb-10'>Web / App Developer</h1>
          <div ref={lottieRef} className="w-72 -mt-6 md:-mt-28 2xl:w-6/12 md:w-5/12 md:mb-10"></div>
          <h1 className='text-center text-lg text-white font-extrabold -mt-6 mb-10 md:-mt-32 md:text-2xl lg:text-6xl 2xl:text-5xl'>Creating Applications with Precision and Passion</h1>
          <p></p>
        </div>
  
          <div className="relative flex py-5 items-center">
            
    <div className="flex-grow border-t border-gray-400"></div>
    <span className="flex-shrink mx-4 text-white text-5xl font-extrabold 2xl:text-8xl">Skills</span>
    <div className="flex-grow border-t border-gray-400"></div>
</div>
          <div className='lg:flex lg:flex-wrap lg:gap-10 mb-20'>
          <div className='justify-center items-center flex flex-col text-white shadow-2xl lg:flex-1'>
            <h3 className='mt-20 font-extrabold text-2xl text-center mb-6 text-sky-400 xl:text-9xl 2xl:text-6xl md:text-5xl'>Design</h3>
            <p className='mb-5 font-semibold text-lg text-center 2xl:text-2xl md:text-2xl'>Photoshop</p>
            <p className='mb-5 font-semibold text-lg text-center 2xl:text-2xl md:text-2xl'>Tailwind</p>
            <p className='mb-5 font-semibold text-lg text-center 2xl:text-2xl md:text-2xl'>Figma</p>
            <p className='mb-5 font-semibold text-lg text-center 2xl:text-2xl md:text-2xl'>SASS</p>
            <p className='mb-5 font-semibold text-lg text-center 2xl:text-2xl md:text-2xl'>CSS</p>
            <p className='mb-5 font-semibold text-lg text-center 2xl:text-2xl md:text-2xl'>MUI</p>
          
          </div>

          <div className='justify-center items-center flex flex-col text-white shadow-2xl lg:flex-1'>
            <h3 className='mt-20 font-extrabold text-2xl mb-10 text-center text-sky-400 2xl:text-6xl md:text-5xl'>Front-End Deveoper</h3>
            <p className='mb-5 font-semibold text-lg text-center 2xl:text-2xl md:text-2xl'>Javascript</p>
            <p className='mb-5 font-semibold text-lg text-center 2xl:text-2xl md:text-2xl'>Typescript</p>
            <p className='mb-5 font-semibold text-lg text-center 2xl:text-2xl md:text-2xl'>NextJs</p>
            <p className='mb-5 font-semibold text-lg text-center 2xl:text-2xl md:text-2xl'>React</p>
            <p className='mb-5 font-semibold text-lg text-center 2xl:text-2xl md:text-2xl'>Redux</p>
            <p className='mb-5 font-semibold text-lg text-center 2xl:text-2xl md:text-2xl'>Vue</p>
          </div>

          <div className='justify-center items-center flex flex-col text-white shadow-2xl lg:flex-1'>
            <h3 className='mt-20 font-extrabold text-2xl mb-6 text-center text-sky-400 2xl:text-6xl md:text-5xl'>Back-End Developer</h3>
            <p className='mb-5 font-semibold text-lg 2xl:text-2xl md:text-2xl'>NodeJS</p>
            <p className='mb-5 font-semibold text-lg 2xl:text-2xl md:text-2xl'>Express</p>
            <p className='mb-5 font-semibold text-lg 2xl:text-2xl md:text-2xl'>Python</p>
            <p className='mb-5 font-semibold text-lg 2xl:text-2xl md:text-2xl'>MongoDB</p>
            <p className='mb-5 font-semibold text-lg 2xl:text-2xl md:text-2xl'>FireBase</p>
            <p className='mb-5 font-semibold text-lg 2xl:text-2xl md:text-2xl'>MySQL</p>
          </div>
          </div>
          <div>
          <div className="relative flex py-5 items-center mb-20">
    <div className="flex-grow border-t border-gray-400"></div>
    <span className="flex-shrink mx-4 text-white text-5xl text-center font-extrabold 2xl:text-8xl">Portfolio</span>
    <div className="flex-grow border-t border-gray-400"></div>
</div>
            <div className='flex flex-col justify-between items-center pl-10 pr-10 gap-5 mb-20 lg:flex lg:flex-row lg:justify-around'>
              <Image src={Aryan} alt='Aryan' className="rounded-lg opacity-80 lg:w-96 lg:h-80 2xl:w-7/12 md:w-3/6"/>
              <Image src={shorty} alt='Aryan' className="rounded-lg opacity-80 lg:w-96 lg:h-80 2xl:w-7/12 md:w-3/6"/>
              <Image src={Dentist} alt='Aryan' className="rounded-lg opacity-80 lg:w-96 lg:h-80 2xl:w-7/12 md:w-3/6"/>
              

            </div>
            </div>
            <div className="relative flex py-5 items-center mb-20">
    <div className="flex-grow border-t border-gray-400"></div>
    <span className="flex-shrink mx-4 text-white text-5xl  text-center font-extrabold 2xl:text-8xl">Client Roster</span>
    <div className="flex-grow border-t border-gray-400"></div>
</div>
           <div className='flex flex-col items-center gap-14 m-12 lg:flex lg:flex-row justify-around 2xl:flex 2xl:flex-row md:flex md:flex-row'>
           <Image src={stjoes} className='w-96 lg:w-96 2xl:w-4/12' alt='Stjoes'/>
           <Image src={flexday} className='w-96 lg:w-80 2xl:w-3/12' alt="flexday"/>
          </div>

          <div className='flex flex-col items-center gap-14 m-12 lg:flex lg:flex-row justify-around 2xl:flex 2xl:flex-row md:flex md:flex-row'>
            <Image src={digikala} className='w-96 lg:w-96 2xl:w-3/12' alt='Digikala'/>
            <Image src={snapp} className='w-80 lg:w-96 2xl:w-3/12' alt='Snapp'/>
          </div>
          <div className='h-10'>
          </div>
        </section>
      </main>
    </>
  )
}

